### ISSUE TITLE
Hello, how many GPUs are required for this task?

### ISSUE THREAD

**Issue by YoucanBaby** [facebookresearch/EgoT2#1]
Hello, how many GPUs are required for this task?

**Comment by zihuixue** [comment]
Hi @YoucanBaby, 

In general, the training of EgoT2 is very lightweight. For the 3 HHI tasks, only 1 GPU is needed for training. For the PNR & OSCC tasks, the default config is 2 GPUs; For the AR & LTA tasks, the default config is 8 GPUs, but feel free to modify the config files about GPU number as you see fit. 

Thanks,
Zihui
