### ISSUE TITLE
A question about the split of the performance on LAM task.

### ISSUE THREAD

**Issue by lemon-prog123** [facebookresearch/EgoT2#4]
Hi! Great job on egocentric videos. I was wondering that which split did you choose when you repo the performance on LAM (that was 77.63%), according to the Table 5 in the paper. Is that the validation split of Ego4D or the test set on Eval AI?

**Comment by zihuixue** [comment]
Hi @lemon-prog123, 

Thanks for the question. The LAM results on Table 5 are based on the validation split of Ego4D. Please let me know if there is any further question!
